services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: benchmark_db
      POSTGRES_USER: benchmark_user
      POSTGRES_PASSWORD: benchmark_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    command: >
      postgres
      -c max_connections=500
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    cpus: 1.0
    mem_limit: 1g
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
      - fastapi_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgres://benchmark_user:benchmark_pass@postgres:5432/benchmark_db
    depends_on:
      - postgres
    cpus: 1.0
    mem_limit: 2g
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.django
    ports:
      - "8001:8001"
    volumes:
      - ./django_app:/app
      - django_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgres://benchmark_user:benchmark_pass@postgres:5432/benchmark_db
    depends_on:
      - postgres
    cpus: 1.0
    mem_limit: 2g
    restart: unless-stopped

volumes:
  postgres_data:
  fastapi_data:
  django_data: