services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    command: >
      mysqld
      --max_connections=10000
      --table_open_cache=2000
      --performance_schema=ON
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=64M
      --innodb_flush_method=O_DIRECT
      --innodb_flush_log_at_trx_commit=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    cpus: 8.0
    mem_limit: 8g
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "18000:8000"
    volumes:
      - ./fastapi_app:/app
      - fastapi_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql://benchmark_user:benchmark_pass@mysql:3306/benchmark_fastapi
      - AERICH_DB=mysql://benchmark_user:benchmark_pass@mysql:3306/benchmark_fastapi
    depends_on:
      - mysql
    cpus: 1.0
    mem_limit: 2g
    restart: unless-stopped

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.django
    ports:
      - "18001:8001"
    volumes:
      - ./django_app:/app
      - django_data:/app/data
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql://benchmark_user:benchmark_pass@mysql:3306/benchmark_django
    depends_on:
      - mysql
    cpus: 1.0
    mem_limit: 2g
    restart: unless-stopped

volumes:
  mysql_data:
  fastapi_data:
  django_data: